spring.application.name=finance-data-processing-service

server.port=${SERVER_PORT:4000}

spring.datasource.url=${APP_DATABASE_URL}
spring.datasource.username=${APP_DATABASE_USERNAME}
spring.datasource.password=${APP_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}
jwt.expiry-time-in-minute=${JWT_EXPIRY_TIME_IN_MINUTE}

rate-limit.bucket.count=${RATE_LIMIT_BUCKET_COUNT:100}
rate-limit.refill.time-in-second=${RATE_LIMIT_REFILL_TIME_IN_SECOND:60}


spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:seed.sql
spring.jpa.defer-datasource-initialization=true

spring.security.user.name=dev
spring.security.user.password=dev