spring.application.name=finance-data-processing-service

server.port=${SERVER_PORT:4000}

spring.datasource.url=${APP_DATABASE_URL}
spring.datasource.username=${APP_DATABASE_USERNAME}
spring.datasource.password=${APP_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiry-time-in-minute=10000